name = "web-summarizer-api"
main = "src/index.ts"
compatibility_date = "2024-10-25"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "web-summarizer-api"
database_id = "e4d5f617-9412-45f4-8b77-e8629e421b48"

[observability]
enabled = true
# head_sampling_rate = 1

[browser]
binding = "BROWSER"

[ai]
binding = "AI"

[triggers]
crons = ["* */1 * * *"]
