name = "web-summarizer-api"
main = "src/index.ts"
compatibility_date = "2024-10-25"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "web-summarizer-api"
database_id = "f5093090-a5ab-45df-aff1-22f961c03868"

[observability]
enabled = true
# head_sampling_rate = 1
