import app from '../lib/app';
import { z, createRoute } from '@hono/zod-openapi';
import { jsonContent } from 'stoker/openapi/helpers';
import * as StatusCodes from 'stoker/http-status-codes';
import { createErrorSchema } from 'stoker/openapi/schemas';
import { notFoundSchema, unauthorizedSchema } from '../lib/constants';
import { TokenSchema } from '../lib/auth';

const IdSchema = z.object({
	id: z.coerce.number({ message: 'Invalid job id' }).openapi({
		title: 'Job ID',
		description: 'Specify this parameter to grab the details of your Job ID.',
		type: 'number',
		format: '#',
		example: 68,
	}),
});

export const JobDetails = z
	.object({
		id: z.number().openapi({
			title: 'Job ID',
			description: 'The ID of the job.',
			type: 'number',
			example: 68,
		}),
		url: z.string().startsWith('https://').openapi({
			title: 'URL',
			description: 'URL that is or will be summarized.',
			type: 'string',
			format: 'https://[domain]/[path]',
			example: 'https://www.iana.org/help/example-domains',
		}),
		status: z.string().openapi({
			title: 'Job Status',
			description: 'The status of this job.',
			type: 'string',
			example: 'completed',
		}),
		summary: z
			.string()
			.optional()
			.openapi({
				title: 'Summary',
				description: 'The summary that was generated by the LLM while summarizing the URL.',
				type: 'string',
				example:
					'We provide a web service on the example domain hosts to provide basic the example domains ' +
					'to have operating HTTP service. available for registration or transfer. The IANA functions ' +
					"coordinate the Internet's globally unique identifiers, and the IANA is used to register and " +
					'transfer domain names.',
			}),
		summary_logs: z.string().optional().openapi({
			title: 'Job Summary Logs',
			description: 'Shows logs generated during the summarizing of the page. Used for debugging purposes.',
			type: 'string',
			example: '7:16:51 AM: Starting job id 68\n7:16:51 AM: Scraping page\n7:16:51 AM: Opening browser',
		}),
		summary_error_message: z.string().optional().openapi({
			title: 'Job Summary Error',
			description: "If something failed during the summarizing of the page, you'll see the reason why here.",
			type: 'string',
			example: '',
		}),
		timestamp: z.coerce.number().openapi({
			title: 'Time Created (UNIX_TIMESTAMP)',
			description: 'The time the job was created.',
			type: 'number',
			example: 1728624263992,
		}),
		started: z.coerce.number().optional().openapi({
			title: 'Time Started (UNIX_TIMESTAMP)',
			description: 'The time the job was picked up by the queue and started.',
			type: 'number',
			example: 1728624270451,
		}),
		finished: z.coerce.number().optional().openapi({
			title: 'Time Finishe (UNIX_TIMESTAMP)d',
			description: 'The time the job was finished.',
			type: 'number',
			example: 1728624285451,
		}),
	})
	.openapi('Job');

const route = createRoute({
	method: 'get',
	path: '/job/{id}',
	request: {
		params: IdSchema,
		query: TokenSchema,
	},
	responses: {
		[StatusCodes.OK]: jsonContent(JobDetails, 'Job Retrieved'),
		[StatusCodes.NOT_FOUND]: jsonContent(notFoundSchema, 'Job ID not found'),
		[StatusCodes.UNAUTHORIZED]: jsonContent(unauthorizedSchema, 'Unauthorized'),
		[StatusCodes.BAD_REQUEST]: jsonContent(createErrorSchema(IdSchema), 'Error'),
	},
});

const getjob = app.openapi(route, async (c) => {
	const { id } = c.req.valid('param');

	return c.json(
		{
			id,
			url: 'https:// - ',
			status: 'asd',
			timestamp: 123123,
		},
		StatusCodes.OK
	);
});

export default getjob;

/*
select: {
	id: true,
	url: true,
	status: true,
	summary: true,
	summary_error_message: true,
	timestamp: true,
},
*/
